/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205757;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * ユニットテストを行うクラス
 */
class FacilitatorTest {
    /**
     * カードを捨てる過程で該当しない番号をカードを入力した場合に手札の枚数が
     */
    @Test void checkHand() {
        Facilitator f = new Facilitator();
        Character p = f.c.get(0);
        f.discard(p, 5);
        f.addCard(p);

        int expected = 5;
        int actual = p.getHand().size();

        assertEquals(actual, expected);
    }
}